### ISSUE TITLE
add support for Google consent "Before you continue" 

### ISSUE THREAD

**Issue by monperrus** [cavi-au/Consent-O-Matic#25]
Google has rolled out a new feature, they now ask for cookie consent. This means that now we have to click dozens of times per day on "Accept" when using Cookie-AutoDelete or a similar extension.

```
Before you continue

Google uses cookies and other data to deliver, maintain, and improve our services and ads. If you agree, we’ll personalize the content and ads you see based on your activity on Google services like Search, Maps, and YouTube. We also have partners that measure how our services are used. Click “See more” to review your options or visit g.co/privacytools anytime.

[I agree]
```

What about adding support for automatic consent to Google's "Before you continue"?

Note: [Google Consent Dialog Remover](https://addons.mozilla.org/en-US/firefox/addon/google-consent-dialog-remover/?src=search) exists but is inactive and requires too many permissions.

**Comment by dkgof** [comment]
Where do you get this popup?

I don't seem to get any even if opening google services in an in private tab with no cookies present.

**Comment by monperrus** [comment]
It appeared two or three days ago on *.google.com,

Maybe it's geography based (I'm in Sweden), or I'm in the wrong part of 
a A/B test or a rollout deployment.

**Comment by monperrus** [comment]
FYI, a working solution based on TamperMonkey: https://stackoverflow.com/a/63999294/1153476

**Comment by raratiru** [comment]
It used to appear scarcely, in Greece. 

It is a couple of weeks now that it pops up constantly, since I clear all cookies on exit.

Guess what... It has all options pre-selected and you have to manually deselect them. Isn't GDPR punishing those opt-out practices or it is just theoretical?... I wonder.

**Comment by Saimyx** [comment]
I have this **** popup with Youtube when I delete cookies

**Comment by Termuellinator** [comment]
Was trying this addon out and noticed this, too.
If anyone is interested: https://www.i-dont-care-about-cookies.eu/de can accept the google-BS. Beware: accepts the cookies, so only advisable with for example temporary containers!

**Comment by kanlukasz** [comment]
Yes, this is the main problem that I would like to solve with this extension

**Comment by svnhub** [comment]
Some CMPs are a little extra complicated and it just so happens that Google is one of those. 

It appears that you cannot actually reject their tracking on the page that they show on the "Before you continue..."-popup, you can only accept them. If you follow through all the sub-pages that they open after you try to select your own preferences and read all the text it turns out that in order to actually reject the cookies you need to download a separate add-on specifically for that purpose.

I'm not sure what to expect from Consent-O-Matic in this case.

**Comment by svnhub** [comment]
Preliminary support (it doesn't understand the categories) for this popup was added in 1.0.2 but Google's way of handling cookies was also recently actually declared illegal in the EU, so we expect them to add a decline button soon

**Comment by piramiday** [comment]
any updates on this?

both Google and YouTube have started showing a "Reject all" button, at least in parts of the EU:


![image](https://user-images.githubusercontent.com/48775554/175488069-7a8790bd-e50d-4351-94a0-e5f8c181704a.png)


![image](https://user-images.githubusercontent.com/48775554/175488152-0ec14e2b-53ae-43f9-af05-df732c6b8b9a.png)

**Comment by dkgof** [comment]
It looks like they might be doing some A/B testing of their new consent interface.

Atm we mostly get the old one still, if they start complying correctly we will implement support for the selections.

**Comment by svnhub** [comment]
I still get a version of the old one when I'm using cabled internet but the new one when on mobile internet... 

![image](https://user-images.githubusercontent.com/13135124/175502335-8358ca09-ea0b-467e-b73d-931878674590.png)

**Comment by sersorrel** [comment]
I edited the builtin google_popup rule to handle the new google and youtube popups; I removed the OPEN_OPTIONS method and added a DO_CONSENT method to press the "accept all"/"reject all" button, which might not be the desired solution for the builtin rule, but it works for me, and is what I'd otherwise do by hand. (this rule also only matches the english translation of the popup, there would be some work to add the text on the buttons in other languages before this could be considered to be as good as the existing builtin rule)

<details><summary>exported JSON rule (click to expand)</summary>

```json
{
    "$schema": "https://raw.githubusercontent.com/cavi-au/Consent-O-Matic/master/rules.schema.json",
    "google_popup": {
        "detectors": [
            {
                "presentMatcher": [
                    {
                        "type": "css",
                        "target": {
                            "selector": "[role=\"dialog\"] a[href^=\"https://policies.google.com/privacy\"]"
                        }
                    },
                    {
                        "type": "css",
                        "target": {
                            "selector": "[role=\"dialog\"] a[href^=\"https://policies.google.com/technologies/cookies\"]"
                        }
                    },
                    {
                        "type": "css",
                        "target": {
                            "selector": "[role=\"dialog\"] a[href^=\"https://policies.google.com/terms\"]"
                        }
                    }
                ],
                "showingMatcher": [
                    {
                        "type": "css",
                        "target": {
                            "selector": "[role=\"dialog\"]",
                            "textFilter": [
                                "g.co/privacytools"
                            ]
                        }
                    }
                ]
            }
        ],
        "methods": [
            {
                "name": "HIDE_CMP"
            },
            {
                "name": "OPEN_OPTIONS"
            },
            {
                "action": {
                    "type": "consent",
                    "consents": [
                        {
                            "trueAction": {
                                "type": "click",
                                "target": {
                                    "selector": "[role=\"dialog\"] button, [role=\"dialog\"] [role=\"button\"]",
                                    "textFilter": [
                                        "Accept all"
                                    ]
                                }
                            },
                            "falseAction": {
                                "type": "click",
                                "target": {
                                    "selector": "[role=\"dialog\"] button, [role=\"dialog\"] [role=\"button\"]",
                                    "textFilter": [
                                        "Reject all"
                                    ]
                                }
                            },
                            "type": "F"
                        }
                    ]
                },
                "name": "DO_CONSENT"
            },
            {
                "name": "SAVE_CONSENT"
            },
            {
                "name": "UTILITY"
            }
        ]
    }
}
```

</details>

**Comment by eric-blabla** [comment]
In the EU this could be country depending. Observe the "Tout refuser" button the French government enforced ! But I still have to click :(
![avant-d-acceder](https://user-images.githubusercontent.com/16685641/180385756-30105ba5-c161-4507-aea7-d92050db8e15.png)

**Comment by Termuellinator** [comment]
Would be really nice if this could be implemented, now that 'i don't care about cookies' is sold out to avast ^^

**Comment by dkgof** [comment]
We have almost completed the needed stuff for handling the google consent form, i think it will be part of the next release.

**Comment by hanacchi** [comment]
any updates on this?

**Comment by endim8** [comment]
shouldn't this be closed as fixed by https://github.com/cavi-au/Consent-O-Matic/pull/169?

**Comment by sersorrel** [comment]
this is working on search and youtube now, but not on maps, for example.

**Comment by justinmayer** [comment]
I can confirm that the Google Maps consent form unfortunately still appears not to be managed properly with Consent-O-Matic v1.0.12 on Safari 16.6.

**Comment by svnhub** [comment]
I think we are getting there by now. They have so many different popups it hurts and they interlink kinda randomly but I think it can be narrowed down to:
1) An EOM dialog popup used on some (but not all) mobile plus some sites where embedding is important for branding. This handles accept/reject but forwards to one of the others if you hit "Customize"
2) Another popup of some sort
3) The cwiz (Consent Wizard?) site 
4) The consent domain for small/mobile devices and for desktop


I just ran through a bunch of the Google services in a private window in Firefox on desktop and mobile and these were the results:
- 📱✅   🖥️ ✅  Google Maps
- 📱✅   🖥️ ✅  Youtube
- 📱✅   🖥️ ✅  Search
- Cloud, no popup, you just accept by default
- Play, no popup
- Mail, no popup

I'm sure this will all change in time, but for now this issue is closed.
